#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-gmaven
Version  : 2.0
Release  : 1
URL      : https://github.com/groovy/gmaven/archive/gmaven-2.0.tar.gz
Source0  : https://github.com/groovy/gmaven/archive/gmaven-2.0.tar.gz
Source1  : https://repo1.maven.org/maven2/org/codehaus/gmaven/gmaven-adapter-api/2.0/gmaven-adapter-api-2.0.jar
Source2  : https://repo1.maven.org/maven2/org/codehaus/gmaven/gmaven-adapter-api/2.0/gmaven-adapter-api-2.0.pom
Source3  : https://repo1.maven.org/maven2/org/codehaus/gmaven/gmaven-adapter-impl/2.0/gmaven-adapter-impl-2.0.jar
Source4  : https://repo1.maven.org/maven2/org/codehaus/gmaven/gmaven-adapter-impl/2.0/gmaven-adapter-impl-2.0.pom
Source5  : https://repo1.maven.org/maven2/org/codehaus/gmaven/gmaven/2.0/gmaven-2.0.pom
Source6  : https://repo1.maven.org/maven2/org/codehaus/gmaven/groovy-maven-plugin/2.0/groovy-maven-plugin-2.0.jar
Source7  : https://repo1.maven.org/maven2/org/codehaus/gmaven/groovy-maven-plugin/2.0/groovy-maven-plugin-2.0.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-gmaven-data = %{version}-%{release}
Requires: mvn-gmaven-license = %{version}-%{release}

%description
<!--
This program is licensed to you under the Apache License Version 2.0,
and you may not use this file except in compliance with the Apache License Version 2.0.
You may obtain a copy of the Apache License Version 2.0 at http://www.apache.org/licenses/LICENSE-2.0.

%package data
Summary: data components for the mvn-gmaven package.
Group: Data

%description data
data components for the mvn-gmaven package.


%package license
Summary: license components for the mvn-gmaven package.
Group: Default

%description license
license components for the mvn-gmaven package.


%prep
%setup -q -n gmaven-gmaven-2.0

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-gmaven
cp LICENSE.txt %{buildroot}/usr/share/package-licenses/mvn-gmaven/LICENSE.txt
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/codehaus/gmaven/gmaven-adapter-api/2.0
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/codehaus/gmaven/gmaven-adapter-api/2.0/gmaven-adapter-api-2.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/codehaus/gmaven/gmaven-adapter-api/2.0
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/codehaus/gmaven/gmaven-adapter-api/2.0/gmaven-adapter-api-2.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/codehaus/gmaven/gmaven-adapter-impl/2.0
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/codehaus/gmaven/gmaven-adapter-impl/2.0/gmaven-adapter-impl-2.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/codehaus/gmaven/gmaven-adapter-impl/2.0
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/org/codehaus/gmaven/gmaven-adapter-impl/2.0/gmaven-adapter-impl-2.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/codehaus/gmaven/gmaven/2.0
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/org/codehaus/gmaven/gmaven/2.0/gmaven-2.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/codehaus/gmaven/groovy-maven-plugin/2.0
cp %{SOURCE6} %{buildroot}/usr/share/java/.m2/repository/org/codehaus/gmaven/groovy-maven-plugin/2.0/groovy-maven-plugin-2.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/codehaus/gmaven/groovy-maven-plugin/2.0
cp %{SOURCE7} %{buildroot}/usr/share/java/.m2/repository/org/codehaus/gmaven/groovy-maven-plugin/2.0/groovy-maven-plugin-2.0.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/codehaus/gmaven/gmaven-adapter-api/2.0/gmaven-adapter-api-2.0.jar
/usr/share/java/.m2/repository/org/codehaus/gmaven/gmaven-adapter-api/2.0/gmaven-adapter-api-2.0.pom
/usr/share/java/.m2/repository/org/codehaus/gmaven/gmaven-adapter-impl/2.0/gmaven-adapter-impl-2.0.jar
/usr/share/java/.m2/repository/org/codehaus/gmaven/gmaven-adapter-impl/2.0/gmaven-adapter-impl-2.0.pom
/usr/share/java/.m2/repository/org/codehaus/gmaven/gmaven/2.0/gmaven-2.0.pom
/usr/share/java/.m2/repository/org/codehaus/gmaven/groovy-maven-plugin/2.0/groovy-maven-plugin-2.0.jar
/usr/share/java/.m2/repository/org/codehaus/gmaven/groovy-maven-plugin/2.0/groovy-maven-plugin-2.0.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-gmaven/LICENSE.txt
